services:
  web:
    tty: true #keep container running
    stdin_open: true #keep container running
    build: .
    ports:
      - 80:80
      - 443:443  
    restart: always
    post_start:
    - command: bash ./scripts/getInstanceMetadata.sh
      user: root
      privileged: true
  server:
    build: ../server/
    ports:
      - 8080:8080
    env_file:
      - /.env
    restart: always
