services:
  web:
    tty: true #keep container running
    stdin_open: true #keep container running
    build: .
    ports:
      - 80:80
      - 443:443  
  server:
    build: ../server/
    ports:
      - 8080:8080
    environment: #ensure these are set in shell first
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}