services:
  web:
    tty: true #keep container running
    stdin_open: true #keep container running
    build: .
    ports:
      - 8080:80    
  server:
    build: ../server/
    ports:
      - 8081:8080
    environment: #ensure these are set in shell first
      - AWS_ACCESS_KEY
      - AWS_SECRET_ACCESS_KEY